from smartcard.util import toHexString, toBytes


INS_SELECT = 0xA4
INS_READ_BINARY = 0xB0
INS_UPDATE_BINARY = 0xD6 
INS_READ_RECORDS = 0xB2 
INS_APPEND_RECORD = 0xE2 
INS_GET_CHALLENGE = 0x84 
INS_INTERNAL_AUTHENTICATE = 0x88 
INS_EXTERNAL_AUTHENTICATE = 0x82 
