# Generated by Django 3.0.3 on 2020-02-13 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import loan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(choices=[(1, 'Lab Loan'), (2, 'Home Loan'), (3, 'Return Board'), (4, 'Enable Home Loan'), (5, 'Disable Home Loan'), (6, 'Unknown Operation')])),
            ],
        ),
        migrations.CreateModel(
            name='RaspiTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr_hex', models.CharField(max_length=66, verbose_name='ATR HEX')),
                ('uid', models.CharField(max_length=66, unique=True, verbose_name='Card UID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr_hex', models.CharField(max_length=66, verbose_name='ATR HEX')),
                ('uid', models.CharField(max_length=66, unique=True, verbose_name='Card UID')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('raspi_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan.RaspiTag')),
                ('board_no', models.CharField(max_length=10, unique=True, verbose_name='board number')),
                ('board_type', django_enumfield.db.fields.EnumField(enum=loan.models.BoardType)),
                ('board_status', django_enumfield.db.fields.EnumField(default=1, enum=loan.models.BoardStatus)),
                ('is_board_loaned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loan.StudentCard')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('second_name', models.CharField(max_length=50, verbose_name='second name')),
                ('matricul_no', models.CharField(max_length=10, unique=True, verbose_name='matriculation')),
                ('hrz_no', models.CharField(max_length=10, unique=True, verbose_name='hrz')),
                ('group', django_enumfield.db.fields.EnumField(enum=loan.models.StudentGroup)),
                ('is_home_loan_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.date.today)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Operation')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Board')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Student')),
            ],
        ),
    ]
