# Generated by Django 3.0.3 on 2020-02-26 14:38

from django.db import migrations
import django_enumfield.db.fields
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspitag',
            name='atr_hex',
            field=django_enumfield.db.fields.EnumField(default=2, enum=loan.models.ATRCardType),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='atr_hex',
            field=django_enumfield.db.fields.EnumField(default=1, enum=loan.models.ATRCardType),
        ),
    ]
