# Generated by Django 3.0.3 on 2020-02-17 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.date.today)),
                ('operation', django_enumfield.db.fields.EnumField(default=6, enum=loan.models.Operation)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['semester'],
            },
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['board_no']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['second_name']},
        ),
        migrations.RemoveField(
            model_name='board',
            name='is_board_loaned',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_no',
            field=models.CharField(max_length=3, unique=True, verbose_name='board number'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=loan.models.BoardType),
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.AddField(
            model_name='semesterlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Board'),
        ),
        migrations.AddField(
            model_name='semesterlist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Student'),
        ),
        migrations.AddField(
            model_name='action',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Board'),
        ),
        migrations.AddField(
            model_name='action',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Student'),
        ),
    ]
