# Generated by Django 3.0.3 on 2020-02-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20200217_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='semesterlist',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Semester'),
        ),
    ]
