# Generated by Django 3.0.3 on 2020-02-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200217_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentcard',
            new_name='student_card',
        ),
    ]
