# Generated by Django 3.0.3 on 2020-02-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20200217_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterlist',
            options={},
        ),
    ]
