# Generated by Django 3.0.3 on 2020-02-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200217_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='current_semester',
        ),
    ]
