# Generated by Django 3.0.3 on 2020-03-31 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20200331_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.Board'),
        ),
        migrations.AlterField(
            model_name='action',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.Student'),
        ),
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 16, 52, 23, 873863)),
        ),
    ]
