# Generated by Django 3.0.5 on 2020-04-13 13:16

import datetime
from django.db import migrations, models
import django_enumfield.db.fields
import loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20200331_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.CharField(max_length=20, verbose_name='current state')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='operation',
            field=django_enumfield.db.fields.EnumField(default=7, enum=loan.models.Operation),
        ),
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
