# Generated by Django 3.0.5 on 2020-04-18 15:33

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20200413_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='session',
            name='raspi_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loan.StudentCard'),
        ),
        migrations.AddField(
            model_name='session',
            name='student_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loan.StudentCard'),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=django_fsm.FSMField(default='session_started', max_length=50),
        ),
    ]
