# Generated by Django 3.0.5 on 2020-05-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_session_last_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loan.Action'),
        ),
    ]
