# Generated by Django 3.0.3 on 2020-02-18 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import loan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_no', models.CharField(max_length=3, unique=True, verbose_name='board number')),
                ('board_type', django_enumfield.db.fields.EnumField(default=1, enum=loan.models.BoardType)),
                ('board_status', django_enumfield.db.fields.EnumField(default=1, enum=loan.models.BoardStatus)),
            ],
            options={
                'ordering': ['board_no'],
            },
        ),
        migrations.CreateModel(
            name='RaspiTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr_hex', models.CharField(max_length=66, verbose_name='ATR HEX')),
                ('uid', models.CharField(max_length=66, unique=True, verbose_name='Card UID')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr_hex', models.CharField(max_length=66, verbose_name='ATR HEX')),
                ('uid', models.CharField(max_length=66, unique=True, verbose_name='Card UID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('second_name', models.CharField(max_length=50, verbose_name='second name')),
                ('matricul_no', models.CharField(max_length=10, unique=True, verbose_name='matriculation')),
                ('hrz_no', models.CharField(max_length=10, unique=True, verbose_name='hrz')),
                ('group', django_enumfield.db.fields.EnumField(enum=loan.models.StudentGroup)),
                ('is_home_loan_enabled', models.BooleanField(default=True)),
                ('student_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.StudentCard')),
            ],
            options={
                'ordering': ['second_name'],
            },
        ),
        migrations.CreateModel(
            name='SemesterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Board')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Student')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='raspi_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.RaspiTag'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.date.today)),
                ('operation', django_enumfield.db.fields.EnumField(default=6, enum=loan.models.Operation)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Board')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Student')),
            ],
        ),
    ]
