# Generated by Django 3.0.3 on 2020-03-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20200226_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.Semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='current_semester',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='SemesterList',
        ),
    ]
