# Generated by Django 3.0.3 on 2020-03-31 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200331_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2020, 3, 31, 16, 39, 11, 289620)),
        ),
    ]
