# Generated by Django 3.0.3 on 2020-03-31 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20200331_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 16, 40, 33, 842177)),
        ),
    ]
