# Generated by Django 3.0.5 on 2020-04-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_auto_20200418_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='raspi_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loan.RaspiTag'),
        ),
    ]
