# Generated by Django 3.0.5 on 2020-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20200418_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_action_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
