# Generated by Django 3.1.1 on 2020-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_remove_session_previous_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
